stocker/ledgers/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('new-acquisition', views.new_acquisition),
    path('random-movement', views.random_movement),
    path('ledgers', views.ledgers),
    path('transactions', views.TransactionsView.as_view()),
    path('adjust-ledger/<int:ledger_id>', views.adjust_ledger),
    path('move-ledger/<int:ledger_id>', views.move_ledger),
    path('search-locations', views.locations),
    path('demo-drawer', views.demo_drawer),
]

stocker/stocker/urls.py
from django.contrib import admin
from django.urls import path, include

import debug_toolbar

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('', include('ledgers.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

stocker/ledgers/models.py
from django.db import models


class Conditions(models.TextChoices):
    PRISTINE = 'pristine', 'Pristine'
    DAMAGED = 'damaged', 'Damaged'
    DESTROYED = 'destroyed', 'Destroyed'


class Reasons(models.TextChoices):
    ACQUIRED = 'acquired', 'Acquired'
    SOLD = 'sold', 'Sold'
    LOST = 'lost', 'Lost'
    MISSING = 'missing', 'Missing'
    ADJUSTMENT = 'adjustment', 'Adjustment'
    MOVED = 'moved', 'Moved'


class Statuses(models.TextChoices):
    ON_HAND = 'on_hand', 'On Hand'
    OUT = 'out', 'Out'
    SOLD = 'sold', 'Sold'
    MISSING = 'missing', 'Missing'


class Transaction(models.Model):
    from_ledger = models.OneToOneField('StockLedger', on_delete=models.CASCADE, related_name='from_transaction')
    to_ledger = models.OneToOneField('StockLedger', on_delete=models.CASCADE, related_name='to_transaction')
    created = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField()
    reason = models.CharField(max_length=15, choices=Reasons.choices)
    notes = models.TextField(blank=True)

    @property
    def sku(self):
        return self.from_ledger.sku

    @property
    def book(self):
        return self.from_ledger.book


class StockLedgerManager(models.Manager):
    def unique_locations(self, search_term=""):
        return self.filter(location__icontains=search_term).values_list("location", flat=True).distinct()

    def current_ledgers(self):
        return self.filter(is_current=True).exclude(location__in=["VOID", "Missing"])


class StockLedger(models.Model):
    sku = models.CharField(max_length=100, null=True, blank=True)
    book = models.CharField(max_length=100)
    count = models.IntegerField()
    location = models.CharField(max_length=100)
    condition = models.CharField(max_length=15, choices=Conditions.choices, default=Conditions.PRISTINE)
    status = models.CharField(max_length=15, choices=Statuses.choices, default=Statuses.ON_HAND)
    is_current = models.BooleanField(default=False)

    objects = StockLedgerManager()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.sku:
            self.sku = f"book-{self.pk}"
            self.save()

stocker/ledgers/forms.py
from django import forms
from .models import Reasons
from .factories import create_transaction, create_adjustment


class AdjustLedgerForm(forms.Form):
    count = forms.IntegerField(min_value=0)
    reason = forms.ChoiceField(choices=Reasons.choices)
    notes = forms.CharField(required=False)

    def process(self, ledger):
        transaction = create_adjustment(
            ledger,
            self.cleaned_data["count"],
            self.cleaned_data["reason"],
            self.cleaned_data["notes"]
        )
        return transaction


class MoveLedgerForm(forms.Form):
    quantity = forms.IntegerField(min_value=0)
    to_location = forms.CharField(initial="")

    def process(self, ledger):
        transaction = create_transaction(
            ledger,
            self.cleaned_data["quantity"],
            self.cleaned_data["to_location"],
            ledger.condition,
            reason="Moved"
        )
        return transaction

stocker/ledgers/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View, ListView
import string
import random
from datetime import datetime, timedelta

from .forms import AdjustLedgerForm, MoveLedgerForm
from .models import StockLedger, Transaction, Reasons, Conditions, Statuses
from .factories import create_acquisition, create_random_movement


def home(request):
    return render(request, "ledgers/home.html")

def new_acquisition(request):
    transaction = create_acquisition()
    messages.success(request, f'A new acquisition of {transaction.from_ledger.book} has been recorded.')
    return render(request, "ledgers/new_acquisition.html")

def random_movement(request):
    transaction = create_random_movement()
    messages.success(request, f'A new movement of {transaction.from_ledger.book} has been recorded.')
    return render(request, "ledgers/random_movement.html")

def ledgers(request):
    page = request.GET.get('page', 1)
    book_filter = request.GET.get('book-filter', '')
    condition_filter = request.GET.get('condition-filter', None)

    ledgers = StockLedger.objects.current_ledgers()

    if book_filter:
        ledgers = ledgers.filter(book__icontains=book_filter)
    if condition_filter:
        ledgers = ledgers.filter(condition=condition_filter)

    ledgers = ledgers.all()

    paginator = Paginator(ledgers, 25)
    page_obj = paginator.get_page(page)

    context = {
        "ledgers": ledgers,
        "page_obj": page_obj,
        "book_filter": book_filter,
        "condition_filter": condition_filter,
        "conditions": Conditions.choices,
    }
    if request.htmx:
        template_name = "ledgers/ledgers_partial.html"
    else:
        template_name = "ledgers/ledgers_page.html"
    return render(request, template_name, context)


def adjust_ledger(request, ledger_id):
    ledger = StockLedger.objects.get(id=ledger_id)

    context = {
        "ledger": ledger
    }
    if request.method == "POST":
        form = AdjustLedgerForm(request.POST)
        if form.is_valid():
            form.process(ledger)
            ledgers = StockLedger.objects.current_ledgers()
            paginator = Paginator(ledgers, 25)
            page_obj = paginator.get_page(1)
            context["page_obj"] = page_obj
    else:
        form = AdjustLedgerForm(initial={
            "count": ledger.count
        })

    context["form"] = form
    return render(
        request,
        "ledgers/adjust_modal.html",
        context=context
    )

def move_ledger(request, ledger_id):
    ledger = StockLedger.objects.get(id=ledger_id)

    context = {"ledger": ledger}
    if request.method == "POST":
        form = MoveLedgerForm(request.POST)
        if form.is_valid():
            form.process(ledger)
            ledgers = StockLedger.objects.current_ledgers()
            paginator = Paginator(ledgers, 25)
            page_obj = paginator.get_page(1)
            context["page_obj"] = page_obj
    else:
        form = MoveLedgerForm()

    context["form"] = form

    return render(request, "ledgers/move_modal.html", context=context)

def locations(request):
    search_term = request.GET.get('to_location', '')
    locations = StockLedger.objects.unique_locations(search_term=search_term)
    return render(
        request,
        "ledgers/locations_search.html",
        context={"locations": locations}
    )

def demo_drawer(request):
    closed = True if request.GET.get('close') == "True" else False
    return render(request, 'ledgers/demo_drawer.html', context={'closed': closed})

# Function Based View

def transactions(request):
    page = request.GET.get('page', 1)
    book_filter = request.GET.get('book-filter', '')
    reason_filter = request.GET.get('reason-filter', '')

    transactions = Transaction.objects.filter()
    if book_filter:
        transactions = transactions.filter(from_ledger__book__icontains=book_filter)
    if reason_filter:
        transactions = transactions.filter(reason=reason_filter)

    paginator = Paginator(transactions, 25)
    page_obj = paginator.get_page(page)

    context = {
        'transactions': transactions,
        'page_obj': page_obj,
        'book_filter': book_filter,
        'reason_filter': reason_filter,
        'reasons': Reasons.choices
    }

    if request.htmx:
        template_name = "ledgers/transactions_partial.html"
    else:
        template_name = "ledgers/transactions_page.html"
    return render(request, template_name, context)


# Helper Mixin for HTMX requests; could add more here, like logging,
# debug information. The 'request.htmx' comes from github.com/adamchainz/django-htmx,
# from one of django's core maintainers. it has a few other helpful middleware-enabled
# properties like `current_url`, `target`, `trigger`, etc. Can potentially be useful
# in determining how to render the response. Here, we just use it to say, if
# the request is an htmx ajax request, render the partial. If it's a fully qualified
# request from the browser, render the whole page.

class HtmxMixin(View):
    def get_template_names(self):
        if self.request.htmx:
            template = self.partial_name
        else:
            template = self.template_name
        return [template]

class TransactionsView(HtmxMixin, ListView):
    partial_name = "ledgers/transactions_partial.html"
    template_name = "ledgers/transactions_page.html"
    paginate_by = 25
    model = Transaction
    context_object_name = "transactions"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.book_filter = request.GET.get('book-filter', '')
        self.reason_filter = request.GET.get('reason-filter', '')

    def get_queryset(self):
        transactions = Transaction.objects.select_related('from_ledger', 'to_ledger').order_by('-created')
        if self.book_filter:
            transactions = transactions.filter(from_ledger__book__icontains=self.book_filter)
        if self.reason_filter:
            transactions = transactions.filter(reason=self.reason_filter)
        return transactions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'reasons': Reasons.choices,
            'book_filter': self.book_filter,
            'reason_filter': self.reason_filter
        })
        return context

stocker/ledgers/templates/ledgers/adjust_modal.html
{% extends "ledgers/base.html" %}
{% block base %}

{% if not form.is_bound or form.errors %}
<div class="modal is-active" id="adjust-modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <!-- MODAL CONTENT -->
    <header class="modal-card-head">
      <p class="modal-card-title">Adjust Ledger {{ ledger.sku }}</p>
      <button class="delete" _="on click remove #adjust-modal"></button>
    </header>
    <section class="modal-card-body">

      <form id="adjust-form">
        {{ form.non_field_errors }}
        <div class="field">
          <label class="label">Adjust Quantity</label>
          <div class="control {% if form.count.errors %}has-icons-right{% endif %}">
            <input 
              class="input {% if form.count.errors %}is-danger{% endif %}" 
              type="numbers" 
              placeholder="New Quantity" 
              name="count"
              value="{{ ledger.count }}">

            {% if form.count.errors %}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            {% endif %}

          </div>
          {% if form.count.errors %}
            <p class="help is-danger">The count cannot be negative.</p>
          {% endif %}
        </div>

        <div class="field">
          <label class="label">Reason</label>
          <div class="is-fullwidth control is-expanded select {% if form.fields.reason.errors %}has-icons-right{% endif %}">
            <select name="reason">
              <option selected disabled>Select a Reason</option>
              {% for value, label in form.reason.field.choices %}
                {% if value == reason_filter %}
                  <option value="{{ value }}" selected>{{ label }}</option>
                {% else %}
                  <option value="{{ value }}">{{ label }}</option>
                {% endif %}
              {% endfor %}
            </select>

            {% if form.reason.errors %}
              {% for error in form.reason.errors %}
                <span class="icon is-small is-right">
                  <i class="fas fa-exclamation-triangle">{{ error }}</i>
                </span>
              {% endfor %}
            {% endif %}

          </div>
        </div>
        
        <div class="field">
          <label class="label">Notes</label>
          <div class="control {% if form.notes.errors %}has-icons-right {% endif %}">
            <input 
              class="input {% if form.notes.errors %}is-danger{% endif %}" 
              type="text" 
              name="notes">

            {% if form.notes.errors %}
              <span class="icon is-small is-right">
                <i class="fas fa-exclamation-triangle"></i>
              </span>
            {% endif %}
          </div>
        </div>
      </form>

    </section>

    <!-- MODAL FOOTER/ACTIONS -->
    <footer class="modal-card-foot buttons is-right">
      <button 
        type="submit" 
        hx-include="#adjust-form"
        hx-post="/adjust-ledger/{{ ledger.id }}"
        hx-target="#adjust-modal"
        hx-swap="outerHTML"
        class="button is-success">Save Changes</button>
      <button class="button" _="on click remove #adjust-modal">Cancel</button>
    </footer>
  </div>

  <!-- CLOSE BUTTON-->
  <button 
    class="modal-close is-large" 
    type="button"
    aria-label="close"
    _="on click remove #adjust-modal"
    >Close</button>
</div>
{% elif form.is_bound and not form.errors %}
  <table class="table is-hoverable is-fullwidth is-striped" id="ledgers-table" hx-swap-oob="true">
    <thead>
      <tr>
        <td>SKU</td>
        <td>Book</td>
        <td>Condition</td>
        <td>Location</td>
        <td>Count</td>
        <td><span class="is-pulled-right">Actions</span></td>
      </tr>
    </thead>
    <tbody>
      {% for ledger in page_obj %}
      <tr>
        <td>{{ ledger.sku }}</td>
        <td>{{ ledger.book }}</td>
        <td>{{ ledger.condition }}</td>
        <td>{{ ledger.location }}</td>
        <td>{{ ledger.count }}</td>
        <td>
          <div class="is-pulled-right">
            <button 
              class="button is-primary"
              hx-get="/adjust-ledger/{{ ledger.id }}" 
              hx-target="#modal-wrapper">Adjust</button>
            <button 
              class="button is-primary"
              hx-get="/move-ledger/{{ ledger.id }}" 
              hx-target="#modal-wrapper">Move</button>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

{% endblock %}

stocker/ledgers/templates/ledgers/base_body.html
{% extends "ledgers/base.html" %}
{% load static %}
{% load random_number %}
{% block base %}
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          <img class="logo" src="{% static 'logo.png' %}" width="112">
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>

          <a class="navbar-item" href="/ledgers">
            Ledgers
          </a>

          <a class="navbar-item" href="/transactions">
            Transactions
          </a>
          <span class="navbar-item"><strong>Random Number: {% random_number 1 100 %}</strong></span>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              {% if not user.is_authenticated %}
                <a class="button is-primary" href="{% url 'signup' %}">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light" href="{% url 'login' %}">
                  Log in
                </a>
              {% else %}
                <a class="button is-light" href="{% url 'logout' %}">
                  Log out
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="pb-6">
      <div class="container">
        {% block messages %}
          <div id="notification-container"></div>
        {% endblock %}
        {% block body %}{% endblock %}
      </div>
    </section>
    <div id="demo-drawer">
      <div class="tabs is-boxed is-medium is-right">
        <ul>
          <li class="is-active">
            <a 
              hx-get="demo-drawer?close=False" 
              hx-target="#demo-drawer">
              <span class="icon is-small">
                <i id="chevron" class="fas fa-chevron-up" aria-hidden="true"></i>
              </span>
              <span>Demo Sandbox</span>
            </a>
          </li>
        </ul>
      </div>
      <div id="demo-drawer-wrapper" class="content-hidden">
      </div>
    </div>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
  </body>
{% endblock %}

stocker/ledgers/templates/ledgers/demo_drawer.html
<div id="demo-drawer">
  <div class="tabs is-right is-boxed is-medium">
    <ul>
      <li class="is-active">
        <a 
          hx-get="demo-drawer?close={% if closed %}False{% else %}True{% endif %}" 
          hx-target="#demo-drawer">
          <span class="icon is-small">
            <i 
              id="chevron" 
              class="fas {% if closed %}fa-chevron-up{% else %}fa-chevron-down{% endif %}" 
              aria-hidden="true"></i>
          </span>
          <span>Demo Sandbox</span>
        </a>
      </li>
    </ul>
  </div>
  <div id="demo-drawer-wrapper" {% if closed %}class="content-hidden"{% endif %}>
    <div class="container content is-normal">
      <h1 class="title">Demo Sandbox</h1>
      <button 
        class="button is-primary"
        hx-post="new-acquisition"
        hx-swap="none"
        _="on click toggle [disabled='true'] until htmx:afterOnLoad"
        >Acquire A Book</button>
      <button 
        class="button is-primary"
        hx-post="random-movement"
        hx-swap="none"
        _="on click toggle [disabled='true'] until htmx:afterOnLoad"
        >Move Something Randomly</button>
    </div>
  </div>
</div>

stocker/ledgers/templates/ledgers/demo_modal.html
{% extends "ledgers/base.html" %}
{% block base %}
<div class="modal is-active" id="demo-modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box">
      <p>This is a demo modal.</p>
    </div>
  </div>
  <button 
    class="modal-close is-large" 
    type="button"
    aria-label="close"
    _="on click remove #demo-modal"
    >Close</button>
</div>
{% endblock %}

stocker/ledgers/templates/ledgers/home.html
{% extends "ledgers/base_body.html" %}

{% block body %}
<div id="demo-modal-wrapper"></div>
{% endblock %}

stocker/ledgers/templates/ledgers/ledgers_page.html
{% extends "ledgers/base_body.html" %}
{% load paginator %}
{% block body %}
<h1 class="title">Ledgers</h1>
  <!-- Book Filter -->
<div 
  class="columns filters-wrapper" 
  hx-target="#ledgers-table" 
  hx-include=".ledger-filter"
  hx-push-url="true">
  <div class="column is-one-quarter">
    <input 
      name="book-filter" 
      class="input ledger-filter" 
      type="text" 
      hx-get="ledgers" 
      hx-target="#ledgers-table"
      hx-trigger="keyup changed delay:500ms"
      value="{{ book_filter }}"
      placeholder="Filter by book...">
  </div>

  <!-- Condition Filter -->
  <div class="column is-one-quarter">
    <div class="select">
      <select 
        class="ledger-filter"
        name="condition-filter"
        hx-get="ledgers" 
        hx-target="#ledgers-table"
        value="{{ condition_filter }}"
        >
        <option value="" {% if not condition_filter %}selected{% endif %}>Filter by condition</option>
        {% for value, label in conditions %}
          {% if value == condition_filter %}
            <option value="{{ value }}" selected>{{ label }}</option>
          {% else %}
            <option value="{{ value }}">{{ label }}</option>
          {% endif %}
        {% endfor %}
      </select>
    </div>
  </div>

  <!-- Paginator -->
  <div class="column is-one-half" id="ledger-paginator">
    {% paginator page_obj %}
  </div>

</div>

<div id="ledgers-table">
  {% include "ledgers/ledgers_partial.html" %}
</div>

<div id="modal-wrapper"></div>
{% endblock %}

stocker/ledgers/templates/ledgers/ledgers_partial.html
{% load paginator %}

<!-- Paginator -->

<table class="table is-hoverable is-fullwidth is-striped" id="ledgers-table" hx-swap-oob="true">
  <thead>
    <tr>
      <td>SKU</td>
      <td>Book</td>
      <td>Condition</td>
      <td>Location</td>
      <td>Count</td>
      <td><span class="is-pulled-right">Actions</span></td>
    </tr>
  </thead>
  <tbody>
    {% for ledger in page_obj %}
    <tr>
      <td>{{ ledger.sku }}</td>
      <td>{{ ledger.book }}</td>
      <td>{{ ledger.get_condition_display }}</td>
      <td>{{ ledger.location }}</td>
      <td>{{ ledger.count }}</td>
      <td>
        <div class="is-pulled-right">
          <button 
            class="button is-primary"
            hx-get="/adjust-ledger/{{ ledger.id }}" 
            hx-target="#modal-wrapper">Adjust</button>
          <button 
            class="button is-primary"
            hx-get="/move-ledger/{{ ledger.id }}" 
            hx-target="#modal-wrapper">Move</button>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div id="ledger-paginator" class="column is-one-half" hx-swap-oob="true">
  {% paginator page_obj %}
</div>

stocker/ledgers/templates/ledgers/locations_search.html
{% extends "ledgers/base.html" %}
{% block base %}

<div class="dropdown-content">
  {% if locations %}

    {% for location in locations %}
      <a 
        _="on click remove .is-active from .dropdown then
           put '{{location}}' into #to-location.value
           on click elsewhere remove .is-active from .dropdown"
        class="dropdown-item">
        {{ location }}
      <a>
    {% endfor %}

  {% else %}

    <a class="dropdown-item">Nothing found...</a>

  {% endif %}
</div>

{% endblock %}

stocker/ledgers/templates/ledgers/move_modal.html
{% extends "ledgers/base.html" %}
{% block base %}

{% if not form.is_bound or form.errors %}
  <div class="modal is-active" id="move-modal">
    <div class="modal-background"></div>
    <div class="modal-card" style="width:70%">
      <!-- MODAL CONTENT -->
      <header class="modal-card-head">
        <p class="modal-card-title">Move Ledger {{ ledger.sku }}</p>
        <button class="delete" _="on click remove #move-modal"></button>
      </header>
      <section class="modal-card-body pt-6 pb-6">

        <form id="move-form" action="">
          {{ form.non_field_errors }}

          <div class="level pt-6 pb-6">
            <div class="level-item">
              <div>
                <p><strong>Title</strong>: {{ ledger.book }}</p>
                <p><strong>SKU</strong>: {{ ledger.sku }}</p>
                <p><strong>Location</strong>: {{ ledger.location }}</p>
                <p><strong>Existing Quantity</strong>: {{ ledger.count }}</p>
              </div>
            </div>
            
            <div class="level-item">
              <div class="field">
                <div class="control">
                  <input 
                    name="quantity" 
                    type="number"
                    required
                    max="{{ ledger.count }}"
                    _="on keyup 
                        if my.value > {{ ledger.count }} 
                          show .help with opacity
                          add .is-danger to me
                        else
                          hide .help with opacity
                          remove .is-danger from me
                        "
                    class="input is-large" 
                    value="{{ form.quantity.value }}"
                    placeholder="Quantity">
                </div>
                <p class="help is-danger" style="position: absolute; opacity:0;">The quantity to move cannot exceed the quantity currently in this location.</p>
              </div>
            </div>

            <div class="level-item">
              <span class="icon is-very-large">
                <i class="fas fa-angle-double-right"></i>
              </span>
            </div>

            <div class="level-item">
              <div class="field">
                <div class="control">
                  <div class="dropdown">
                    <div class="dropdown-trigger">
                      <input 
                        required
                        name="to_location" 
                        id="to-location"
                        class="input is-large" 
                        type="text" 
                        hx-get="/search-locations"
                        hx-target="#locations-list"
                        hx-trigger="click keyup changed delay:500ms"
                        _="on htmx:afterOnLoad add .is-active to .dropdown"
                        autocomplete="off"
                        value="{{ form.to_location.value }}"
                        placeholder="Destination Location">
                    </div>
                    <div class="dropdown-menu" id="locations-list">
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="level-item">
              <p class="mt-1"><strong>New Quantity:</strong> {% if move_quantity > ledger.count %} -- {% else %}{{ new_quantity }}{% endif %}</p>
            </div>

          </div>

        </form>

      </section>

      <!-- MODAL FOOTER/ACTIONS -->
      <footer class="modal-card-foot buttons is-right">
        <button 
          type="submit" 
          hx-include="#move-form"
          hx-post="/move-ledger/{{ ledger.id }}"
          hx-target="#move-modal"
          hx-swap="outerHTML"
          class="button is-success">Save Changes</button>
        <button class="button" _="on click remove #move-modal">Cancel</button>
      </footer>
    </div>

    <!-- CLOSE BUTTON-->
    <button 
      class="modal-close is-large" 
      type="button"
      aria-label="close"
      _="on click remove #move-modal"
      >Close</button>
  </div>
{% elif form.is_bound and not form.errors %}
  <table class="table is-hoverable is-fullwidth is-striped" id="ledgers-table" hx-swap-oob="true">
    <thead>
      <tr>
        <td>SKU</td>
        <td>Book</td>
        <td>Condition</td>
        <td>Location</td>
        <td>Count</td>
        <td><span class="is-pulled-right">Actions</span></td>
      </tr>
    </thead>
    <tbody>
      {% for ledger in page_obj %}
      <tr>
        <td>{{ ledger.sku }}</td>
        <td>{{ ledger.book }}</td>
        <td>{{ ledger.condition }}</td>
        <td>{{ ledger.location }}</td>
        <td>{{ ledger.count }}</td>
        <td>
          <div class="is-pulled-right">
            <button 
              class="button is-primary"
              hx-get="/adjust-ledger/{{ ledger.id }}" 
              hx-target="#modal-wrapper">Adjust</button>
            <button 
              class="button is-primary"
              hx-get="/move-ledger/{{ ledger.id }}" 
              hx-target="#modal-wrapper">Move</button>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}
{% endblock %}

stocker/ledgers/templates/ledgers/new_acquisition.html
{% if messages %}
  <div id="notification-container" hx-swap-oob="true">
  {% for message in messages %}
    <div class="notification is-primary">
      <button class="delete" _="on click remove my.parentElement"></button>
      {{ message }}
    </div>
  {% endfor %}
  </div>
{% endif %}

stocker/ledgers/templates/ledgers/random_movement.html
{% if messages %}
  <div id="notification-container" hx-swap-oob="true">
  {% for message in messages %}
    <div class="notification is-primary">
      <button class="delete" _="on click remove my.parentElement"></button>
      {{ message }}
    </div>
  {% endfor %}
  </div>
{% endif %}

stocker/ledgers/templates/ledgers/test_transition.html
<div id="transition-demo" class="fade-in">
  <p>This should fade in.</p>
</div>

stocker/ledgers/templates/ledgers/transactions.html
{% extends "ledgers/base_body.html" %}
{% block body %}
<h1>Transactions</h1>
{% endblock %}

stocker/ledgers/templates/ledgers/transactions_partial.html
</div>

<table class="table is-hoverable is-fullwidth is-striped" id="transactions-table">
  <thead>
    <tr>
      <td>SKU</td>
      <td>Book</td>
      <td>Created</td>
      <td>Qty</td>
      <td>From</td>
      <td>To</td>
      <td>Reason</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transactions %}
    <tr>
      <td>{{ transaction.sku }}</td>
      <td>{{ transaction.book }}</td>
      <td>{{ transaction.created }}</td>
      <td>{{ transaction.quantity }}</td>
      <td>{{ transaction.from_ledger.get_status_display }}</td>
      <td>{{ transaction.to_ledger.get_status_display }}</td>
      <td>{{ transaction.get_reason_display }}</td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>